apiVersion: batch/v1
kind: Job
metadata:
  name: mysql-migration
spec:
  template:
    spec:
      containers:
      - name: mysql-db-creator
        image: mysql:8.0
        command: 
          - "sh"
          - "-c"
          - "mysql -h mysql-0.mysql  -uroot -prootpassword -e 'CREATE DATABASE IF NOT EXISTS login CHARACTER SET utf8;'"
      restartPolicy: Never
  backoffLimit: 4
